# Generated by Django 5.1.7 on 2025-04-02 04:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gemini_api_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Gemini API密钥",
                    ),
                ),
                (
                    "email_password",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱密码"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="用户中文名"
                    ),
                ),
                (
                    "email_signature_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="邮件签名名称",
                    ),
                ),
                (
                    "email_signature_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="邮件签名电话",
                    ),
                ),
                (
                    "email_from",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="发件人邮箱"
                    ),
                ),
                (
                    "email_to",
                    models.TextField(
                        blank=True,
                        help_text="多个收件人用逗号分隔",
                        null=True,
                        verbose_name="收件人邮箱",
                    ),
                ),
                (
                    "smtp_server",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="SMTP服务器"
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                        verbose_name="SMTP端口",
                    ),
                ),
                (
                    "send_time",
                    models.TimeField(blank=True, null=True, verbose_name="发送时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="启用报告"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户设置",
                "verbose_name_plural": "用户设置",
            },
        ),
    ]
