# Generated by Django 5.1.7 on 2025-04-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0002_monthlyplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="send_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="每月需要发送报告的日期，JSON数组格式",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="email_from",
            field=models.EmailField(
                blank=True, help_text="发件人邮箱", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="email_password",
            field=models.CharField(
                blank=True, help_text="邮箱密码/授权码", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="email_signature_name",
            field=models.CharField(
                blank=True, help_text="邮件签名姓名", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="email_signature_phone",
            field=models.CharField(
                blank=True, help_text="邮件签名电话", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="email_to",
            field=models.CharField(
                blank=True,
                help_text="收件人邮箱，多个用逗号分隔",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="gemini_api_key",
            field=models.CharField(
                blank=True, help_text="Gemini API密钥", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="is_active",
            field=models.BooleanField(default=False, help_text="是否启用自动发送"),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="send_time",
            field=models.TimeField(blank=True, help_text="每日发送时间", null=True),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="smtp_port",
            field=models.IntegerField(
                blank=True, help_text="SMTP服务器端口", null=True
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="smtp_server",
            field=models.CharField(
                blank=True, help_text="SMTP服务器地址", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="user_name",
            field=models.CharField(
                blank=True,
                help_text="用户中文名，用于邮件标题",
                max_length=50,
                null=True,
            ),
        ),
    ]
