# Generated by Django 5.1.7 on 2025-04-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reporter",
            "0003_usersettings_send_days_alter_usersettings_email_from_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="use_client_proxy",
            field=models.BooleanField(
                default=False, help_text="使用客户端代理访问Gemini API"
            ),
        ),
    ]
