# Generated by Django 5.1.7 on 2025-04-02 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0004_usersettings_use_client_proxy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Success", "成功"),
                            ("Failed", "失败"),
                            ("No Content", "无内容"),
                        ],
                        default="Success",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="邮件主题"
                    ),
                ),
                (
                    "content_preview",
                    models.TextField(blank=True, verbose_name="内容预览"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "邮件日志",
                "verbose_name_plural": "邮件日志",
                "ordering": ["-send_timestamp"],
            },
        ),
    ]
