# Generated by Django 5.1.7 on 2025-04-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporter", "0005_emaillog"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="gemini_timeout",
            field=models.IntegerField(
                default=15, help_text="Gemini API请求超时时间（秒）"
            ),
        ),
    ]
