# Generated by Django 5.1.7 on 2025-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_usersettings_gemini_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='定时发送'),
        ),
    ]
