# Generated by Django 5.1.7 on 2025-04-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_add_is_scheduled_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='is_scheduled',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='定时发送'),
        ),
    ]
