# Generated by Django 5.1.7 on 2025-04-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_alter_emaillog_is_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='use_hf_proxy',
            field=models.BooleanField(default=False, help_text='使用HuggingFace代理绕过Gemini地域限制'),
        ),
    ]
