# Generated by Django 5.1.7 on 2025-04-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_usersettings_use_hf_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='use_hf_proxy',
            field=models.BooleanField(default=True, help_text='使用HuggingFace代理绕过Gemini地域限制'),
        ),
    ]
